[itau_openfinance]
client_id = "8e41eac8-2cb1-3d62-8f09-b36ae2eb3029"
client_secret = "8e41eac8-2cb1-3d62-8f09-b36ae2eb3029"
static_access_token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4ZTQxZWFjOC0yY2IxLTNkNjItOGYwOS1iMzZhZTJlYjMwMjkiLCJleHAiOjE3NTk5Mjk4MzQsImlhdCI6MTc1OTkyOTUzNCwic291cmNlIjoic3RzLXNhbmRib3giLCJlbnYiOiJQIiwiZmxvdyI6IkNDIiwic2NvcGUiOiJjYXNobWFuYWdlbWVudC1jb25zdWx0YWJvbGV0b3MtdjEtYXdzLXNjb3BlIiwidXNlcm5hbWUiOiJyc2VsbWlrYWl0aXNAZ21haWwuY29tIiwib3JnYW5pemF0aW9uTmFtZSI6IkF1dG8gQ2FkYXN0cm8ifQ.VpU2u7paU0msZJLVS5dazqHe5Ahc7v4vuyFWF9tCQd4"
scope = "cashmanagement-consultaboletos-v1-aws-scope"
base_url = "https://sandbox.devportal.itau.com.br/itau-x0-api-account-statement-v1-externo/v1"
accounts_endpoint = "/accounts"
transactions_endpoint = "/accounts/{account_id}/transactions"
additional_headers = "{}"
